<a href="https://colab.research.google.com/github/pd05849/Machine_Learning_Engineering/blob/main/Softmax_trainig.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Create a feature vector
feature_vector = np.array([1, 2, 3, 4, 5])
print("Feature Vector:")
print(feature_vector)

# Create a weight matrix (e.g., for a simple linear model)
# The number of columns in the weight matrix should match the number of features
num_features = len(feature_vector)

# k is the number of things we want to classify
k = 3 # Example: 3 classes
num_outputs = k

weight_matrix = np.random.rand(num_outputs, num_features)
print("\nWeight Matrix:")
print(weight_matrix)

Feature Vector:
[1 2 3 4 5]

Weight Matrix:
[[0.65000518 0.66079758 0.98218504 0.13454539 0.57418185]
 [0.02493839 0.38243901 0.33881674 0.31835819 0.84131011]
 [0.877871   0.94573789 0.79069642 0.15140229 0.6166123 ]]


In [3]:
z = np.dot(weight_matrix, feature_vector)
print("\nDot Product (z):")
print(z)


Dot Product (z):
[8.3272463  7.28624995 8.83010667]


In [4]:
softmax = np.exp(z) / np.sum(np.exp(z))
print("\nSoftmax Output:")
print(softmax)


Softmax Output:
[0.33260751 0.11744461 0.54994788]


In [8]:
import numpy as np

# Create a feature vector
feature_vector = np.array([1, 2, 0, 1])
print("Feature Vector:")
print(feature_vector)

# Create a weight matrix (e.g., for a simple linear model)
# The number of columns in the weight matrix should match the number of features
num_features = len(feature_vector)

# k is the number of things we want to classify
k = 3 # Example: 3 classes
num_outputs = k

weight_matrix = np.array([[0.2, 0.5, -0.3, 0.1], [-0.4, 0.3, 0.8, 0.2], [0.1, -0.2, 0.4, 0.6]])
print("\nWeight Matrix:")
print(weight_matrix)

b = np.array([0.1, -0.2, 0.3])
print("\nb Vector:")
print(b)

z = np.dot(weight_matrix, feature_vector) * b
print("\nDot Product (z):")
print(z)

softmax = np.exp(z) / np.sum(np.exp(z))
print("\nSoftmax Output:")
print(softmax)

predicted_class = np.argmax(softmax)
print("\nPredicted Class:")
print(predicted_class)

# Create one-hot encoded prediction
one_hot_prediction = np.zeros(num_outputs)
one_hot_prediction[predicted_class] = 1
print("\nOne-Hot Encoded Prediction:")
print(one_hot_prediction)

Feature Vector:
[1 2 0 1]

Weight Matrix:
[[ 0.2  0.5 -0.3  0.1]
 [-0.4  0.3  0.8  0.2]
 [ 0.1 -0.2  0.4  0.6]]

Dot Product (z):
[1.3 0.4 0.3]

Softmax Output:
[0.56355519 0.22912444 0.20732037]

Predicted Class:
0

One-Hot Encoded Prediction:
[1. 0. 0.]


In [12]:
import numpy as np

# Create a feature vector
feature_vector = np.array([1, 2, 0, 1])
print("Feature Vector:")
print(feature_vector)

# Create a weight matrix (e.g., for a simple linear model)
# The number of columns in the weight matrix should match the number of features
num_features = len(feature_vector)

# k is the number of things we want to classify
k = 3 # Example: 3 classes
num_outputs = k

weight_matrix = np.array([[0.2, 0.5, -0.3, 0.1], [-0.4, 0.3, 0.8, 0.2], [0.1, -0.2, 0.4, 0.6]])
print("\nWeight Matrix:")
print(weight_matrix)

b = np.array([0.1, -0.2, 0.05])
print("\nb Vector:")
print(b)

z = np.dot(weight_matrix, feature_vector) + b
print("\nDot Product (z):")
print(z)

softmax = np.exp(z) / np.sum(np.exp(z))
print("\nSoftmax Output:")
print(softmax)

predicted_class = np.argmax(softmax)
print("\nPredicted Class:")
print(predicted_class)

# Create one-hot encoded prediction
one_hot_prediction = np.zeros(num_outputs)
one_hot_prediction[predicted_class] = 1
print("\nOne-Hot Encoded Prediction:")
print(one_hot_prediction)

Feature Vector:
[1 2 0 1]

Weight Matrix:
[[ 0.2  0.5 -0.3  0.1]
 [-0.4  0.3  0.8  0.2]
 [ 0.1 -0.2  0.4  0.6]]

b Vector:
[ 0.1  -0.2   0.05]

Dot Product (z):
[1.4  0.2  0.35]

Softmax Output:
[0.60564511 0.1824168  0.21193809]

Predicted Class:
0

One-Hot Encoded Prediction:
[1. 0. 0.]
